apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.19.255.200-172.19.255.250

#kubectl apply -fhttps://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml      
#kubectl apply -fhttps://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
#
#kubectl apply -f metallb-configmap.yaml